#pragma once

// Set variables from CMakeLists.txt in src folder
#define APP_ASSETS_DIR "${LIB_SMART_CAR_ASSETS_DIR}"
#define APP_NN_MODELS_DIR "${LIB_SMART_CAR_NN_MODELS_DIR}"
#define APP_SHADER_DIR "${LIB_SMART_CAR_SHADER_DIR}"
#define APP_SERIALIZED_FILES_DIR "${LIB_SMART_CAR_SERIALIZED_FILES_DIR}"